apiVersion: v1
kind: Service
metadata:
  name: ${app_name}-mariadb
spec:
  type: ClusterIP
  clusterIP: ${mariadb_ip}
  selector:
    app: ${app_name}-mariadb
  ports:
    - name: "mariadb"
      protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${app_name}-mariadb
  labels:
    app: ${app_name}-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${app_name}-mariadb
  template:
    metadata:
      labels:
        app: ${app_name}-mariadb
    spec:
      volumes:
      - name: ${app_name}-web-conf
        configMap:
          name: ${app_name}-web-conf

      - name: ${app_name}-mariadb-storage
        hostPath:
          path: "${target_deploy_path}/${app_name}-mariadb-pv"

      - name: ${app_name}-logs
        hostPath:
          path: "${target_deploy_path}/${app_name}-logs-pv"

      imagePullSecrets:
        - name: ${img_pull_sec}

      containers:
      - name: mariadb
        image: "${mariadb_image}"
        imagePullPolicy: IfNotPresent
        ports:
          - name: "mariadb-server"
            containerPort: 3306
        volumeMounts:
          - name: ${app_name}-mariadb-storage
            mountPath: /var/lib/mysql
          - name: ${app_name}-web-conf
            mountPath: "/etc/mysql/mariadb.cnf"
            subPath: "mariadb.cnf"
          - name: ${app_name}-logs
            mountPath: "/var/log"
        resources:
          limits:
            cpu: "200m"
            memory: "512M"
        env:
          # Use secret in real usage
          - name: MYSQL_ROOT_PASSWORD
            value: ${mariadb_root_pass}
