apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${app_name}-netbird-rp
  labels:
    app: ${app_name}-netbird-rp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${app_name}-netbird-rp
  template:
    metadata:
      labels:
        app: ${app_name}-netbird-rp
    spec:
      containers:
        - name: reverse-proxy
          image: ${netbird_image}
          ports:
            - containerPort: 8080
            - containerPort: 8043
          env:
            - name: NB_PROXY_CERTIFICATE_DIRECTORY
              value: "${netbird_rp_certificates_dir}"
            - name: NB_PROXY_ALLOW_INSECURE
              value: "${netbird_rp_allow_insecure}"
            - name: NB_PROXY_MANAGEMENT_ADDRESS
              value: "${netbird_rp_management_address}"
            - name: NB_PROXY_ACME_CERTIFICATES
              value: "${netbird_rp_acme_cert}"
            - name: NB_PROXY_DOMAIN
              value: "${netbird_proxy_domain}"
            - name: NB_PROXY_LOG_LEVEL
              value: "${netbird_proxy_domain}"
            - name: NB_PROXY_TOKEN
              value: "${netbird_proxy_token}"
            - name: NB_PROXY_PRIVATE
              value: "${netbird_proxy_private}"
            - name: NB_PROXY_ADDRESS
              value: "${netbird_proxy_address}"
          volumeMounts:
            - name: certs
              mountPath: /certs
      volumes:
        - name: certs
          hostPath:
            path: /opt/noctialisy/deploys/certs

---
apiVersion: v1
kind: Service
metadata:
  name: ${app_name}-netbird-rp
spec:
  type: ClusterIP
  clusterIP: ${netbird_ip}
  selector:
    app: ${app_name}-netbird-rp
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 8043
      targetPort: 8043