apiVersion: v1
kind: Service
metadata:
  name: ${app_name}-seafile
spec:
  selector:
    app: ${app_name}-seafile
  type: ClusterIP
  clusterIP: ${seafile_ip}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${app_name}-seafile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${app_name}-seafile
  template:
    metadata:
      labels:
        app: ${app_name}-seafile
    spec:
      containers:
        - name: ${app_name}-seafile
          #        image: seafileltd/seafile-mc:9.0.10
          #        image: seafileltd/seafile-mc:11.0-latest
          #        image: seafileltd/seafile-pro-mc:13.0-latest
          image: ${seafile_image}
          env:
            - name: SEAF_SERVER_STORAGE_TYPE
              value: "true"
            - name: INIT_S3_STORAGE_BACKEND_CONFIG
              value: "true"
            - name: INIT_S3_COMMIT_BUCKET
              value: "seafile-commit-objects"
            - name: INIT_S3_FS_BUCKET
              value: "seafile-fs-objects"
            - name: INIT_S3_BLOCK_BUCKET
              value: "seafile-block-objects"
            - name: INIT_S3_KEY_ID
              value: "${seafile_s3_key_id}"
            - name: INIT_S3_SECRET_KEY
              value: "${seafile_s3_secret_key}"
            - name: INIT_S3_HOST
              value: "${seafile_s3_host}" # Do not include http/https here
            - name: INIT_S3_AWS_REGION
              value: "${seafile_s3_aws_region}"
            - name: INIT_S3_USE_HTTPS
              value: "true"
            - name: INIT_S3_USE_V4_SIGNATURE
              value: "true"
            - name: DB_HOST
              value: "${seafile_db_host}"
            - name: DB_ROOT_PASSWD
              value: "${seafile_db_root_password}" #db's password
            - name: TIME_ZONE
              value: "${seafile_time_zone}"
            - name: SEAFILE_ADMIN_EMAIL
              value: "${seafile_admin_email}" #admin email
            - name: SEAFILE_ADMIN_PASSWORD
              value: "${seafile_admin_password}" #admin password
            - name: SEAFILE_SERVER_LETSENCRYPT
              value: "${seafile_server_letsenencrypt}"
            - name: SEAFILE_SERVER_HOSTNAME
              value: "${seafile_server_hostname}" #hostname
          ports:
            - containerPort: 80
          #        - containerPort: 443
          #          name:  seafile-secure
          volumeMounts:
            - name: seafile-data
              mountPath: /shared
      volumes:
        - name: seafile-data
          hostPath:
            path: ${target_deploy_path_protected}/${app_name}-seafile-data
      restartPolicy: Always
      # to get image from protected repository
      imagePullSecrets:
        - name: regcred